### ISSUE TITLE
ESP32: DigitalPulse causes crashes

### ISSUE THREAD

**Issue by chevdor** [espruino/Espruino#1228]
DigitalPulse was initially not working for the ESP32. It has been fixed in #1175 
I am using the cuttingEdge from 2017-08-24 on a ESP32-WROOM32 Devkit.

Issue: Calling digitalPulse several times causes a crash.

The following sample does 'count' as expected, way above 200.
```
var count=0;

function blip() {
  //digitalPulse(18, 1, 15);
  console.log(count++);
}

function start() {
  setInterval(blip, 30);
}

E.on('init', start);
```

The following code however, never reaches 200, and crashes after an apparently random number of crashes. During the test, until it crashes, the pulses are correct:
![ds1z_quickprint5](https://user-images.githubusercontent.com/738724/29707967-6d8bb138-8987-11e7-8263-1d34dffaf8e2.png)
 
```
var count=0;

function blip() {
  digitalPulse(18, 1, 15);
  console.log(count++);
}

function start() {
  setInterval(blip, 30);
}

E.on('init', start);
```

The crash occurs usually between count ~=30 to 120.
I have seen few examples where it runs without problem above 300 so you may have to run the  code a few times before catching the issue but the failure rate is high. If you wait 10s, you will see the issue a few times as shown below.

![ds1z_quickprint4](https://user-images.githubusercontent.com/738724/29707975-74dfc5aa-8987-11e7-9d66-4428878a2d9e.png)

Here is a dump:
```
...
8
9
10
11
>abort() was called at PC 0x400827ef on core 0
Backtrace: 0x400876ac:0x3ffb0470 0x400877ab:0x3ffb0490 0x400827ef:0x3ffb04b0 0x400828dd:0x3ffb04e0 0x400d323a:0x3ffb0500 0x400829b8:0x3ffb0520 0x40115059:0x3ffb0540 0x40100e41:0x3ffb0560 0x400e68e0:0x3ffb0590 0x40082b1f:0x3ffb05e0 0x400816f5:0x3ffb0600
================= CORE DUMP START =================
nBwAAAkAAAB0AQAA
GP36P4DS/D/k0/w/
gNL8P4DT/D9aK2utlCf7P5Qn+z8Y/fo/jCf7PxkAAAAXNnv9ECYqCxj9+j8AAAAA
AAAAAOjP/D9JRExFAGxHvAFslchBuikAAAAAAOTT/D8AAAAAIQAGAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFjj+j/A4/o/KOT6PwAAAAAAAAAA
AQAAAAAAAAB4KUA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdE8
uBQIQPRYEkAwCAYAOFwIgEDT/D8IAAAAAQAAACMABgAY/fo/AQAAAAAAAADYM/s/
INP8PwAAAAAgCAYAIQAGALD6+j8kCPs/IAcGAAAAAACA0/w/AAAAAAAAAAAAAAAA
AAAAALUWCECw+vo/gGgIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYNP8PwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAACA0/w/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjNP8PwAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA=
aO/8P3Dt/D9c7/w/
cO38P/Du/D/qAwAAgCf7Pwzi/T9o7/w/eCf7PwcAAABk5Pw/ZOT8P2jv/D9c5Pw/
EgAAAGDl/D90aVQAr+8KTxRY0T78o0YA////f1zv/D8AAAAAIQAGABIAAAABAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFjj+j/A4/o/KOT6PwAAAAAAAAAA
AQAAAAAAAAB4KUA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZaay
uBQIQMVPCEAwDAYAbF8VgDDu/D845Pw/wO78P4Dk/D8AAAAAAQAAAAMAAACQUAiA
EO78P9wA8D8BAAAAgCn7PwAAAAAAAAAAAAAAAB8AAAC4FAhAVKIUQODCAED2wgBA
/////7UWCEAAAAAAgGgIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAACleFYBA7vw/4MIAQPbCAECI4xSAcO78Pzhg+z/A7vw/
AAAAAIYDAAAAAAAAAAAAAGQAAAAAAAAAAAAAAAAAAACs4xSAgO78PwAAAAAsKghA
C5QUgKDu/D84YPs/wO78PwuUFICg7vw/OGD7P8Du/D9kAAAAhgMAAAAAAAAAAAAA
AAAAAMDu/D/0dRVAAAAAALziFEAAAAAAAQAAAAAAAAAAAAAA8O78PwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAD87vw/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
BOL9P7Df/T/44f0/
sN/9P5Dh/T+eAwAAcO/8P4An+z8E4v0/eCf7PwUAAADY6f0/2On9PwTi/T/Q6f0/
FAAAACza/T91YXJ0VGFzawDGeMwlCSQAAAAAAPjh/T8AAAAAIQAGABQAAAABAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFjj+j/A4/o/KOT6PwAAAAAAAAAA
AQAAAAAAAAB4KUA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAk6Xz
uBQIQMVPCEAwCAYAYG8IgHDg/T+s6f0/AAAAAPTp/T8AAAAAAQAAAAMAAACQUAiA
UOD9P9wA8D8BAAAAgCn7P7Ti+j8RAAAAgOP9Pw8AAAA0vv0/tOL6P2zEAEB3xABA
AAAAALUWCEC04vo/gGgIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAQ3EkCA4/0/jOP9PwMAAADtcQiAsOD9PxTl/T8AAAAA
AAAAADoDAABsM/s/gOP9P2QAAAAAAAAAjOP9P5AM+z+4Dw+A8OD9PwAAAABI4f0/
0ksSgODg/T8U5f0/EOH9PxDh/T8KCngApaWlpaWlpaVkAAAAAAAAAFDl/T9Q5f0/
9g8PgADh/T8AAAAAtKf8P2QAAAAAAAAAAAAAAAAAAAD1FxCAUOH9PwAAAAAAAAAA
AAAAAHDh/T8AAAAAAAAAAADCAQADAAAAAAAAAAEAAAAAAAAAegAAAP//////////
AAEAAGQAAAAAAAAAgOP9PwAAAABw4f0/AAAAAAAAAAAjAAYABOL9PwEAAAAAAAAA
AAAAAJDh/T8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAACc4f0/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA=
+Nv8P5Da/D/s2/w/
kNr8P4Db/D8AAAAAbCf7P2wn+z/42/w/ZCf7PxgAAADA/vo/wP76P/jb/D+4/vo/
AQAAAPDT/D9UbXIgU3ZjAMyK2Wja7+MAAAAAAOzb/D8AAAAAIQAGAAEAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFjj+j/A4/o/KOT6PwAAAAAAAAAA
AQAAAAAAAAB4KUA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0Jax
uBQIQONnCEAwAAYAAAAAAFDb/D8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADjZwiA
INv8P4gp+z8AAAAAAQAAAJz7+j8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAALUWCECc+/o/gGgIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgNv8PwAAAAAAAAAA
AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAACM2/w/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
ULz9P7C6/T9EvP0/
sLr9P+C7/T9kwYbMjE/9PyDq+j9QvP0/HCf7PwQAAABssf0/bLH9P1C8/T9ksf0/
FQAAAEiy/T9wbVQA/PkuWWioVxADLKYA////f0S8/T8AAAAAIQAGABUAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFjj+j/A4/o/KOT6PwAAAAAAAAAA
AQAAAAAAAAB4KUA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKv0o
uBQIQMVPCEAwAgYApbwTgHC7/T9Asf0/sLv9P4ix/T8AAAAAAQAAAAAAAACQUAiA
ULv9P9wA8D8BAAAAgCn7PyA+/T8KAAAAAAAAAAAAAAClpaWlpaWlpeDCAED2wgBA
/////7UWCEAgPv0/gGgIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsLv9PzhH+z9sjkE/
AAAAABcAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAOC7/T8AAAAAAAAAAAEAAAAAAAAAAAAAAAAAAABQSPs/CAEAADhH+z8AAAAg
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7Lv9PwAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA=
hE/9P8BN/T94T/0/
wE39PxBP/T9bU/uIAM39P1i8/T+ET/0/HCf7PwUAAABUQf0/VEH9P4RP/T9MQf0/
FAAAAHxH/T9ldmVudFRhc2sAs4G3wn0AAAAAAHhP/T8AAAAAIQAGABQAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFjj+j/A4/o/KOT6PwAAAAAAAAAA
AQAAAAAAAAB4KUA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArQxP
uBQIQMVPCEAwBAYA0FcSgIBO/T8oQf0/wE79P3BB/T8AAAAAAQAAAAAAAACQUAiA
YE79P9wA8D8BAAAAgCn7P7A+/T8DAAAAhAz7PwAAAAAAAAAAAAAAAODCAED2wgBA
/////7UWCECwPv0/gGgIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAMCoBAH///8AwKgEASQKxAUAAAAAwE79PwAAAAAAAAAA
AAAAABkAAAADAAAAhAz7P//////ATv0/AAAAAAAAAABwQf0/AAAAAERH/T8AAAAA
AAAAABBP/T8AAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAGAAAAStD9P///AADEBgAA
qGxBPyQAAAACAAAAmDT7PwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAcT/0/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAA=
+Mz9P1DL/T/szP0/
UMv9P4DM/T+qAzchfGj9P4xP/T/4zP0/HCf7PwMAAAB4vv0/eL79P/jM/T9wvv0/
FgAAAPC+/T9ydFQAsfOQISNht8/XmzwA////f+zM/T8AAAAAIQAGABYAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFjj+j/A4/o/KOT6PwAAAAAAAAAA
AQAAAAAAAAB4KUA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4bQX
uBQIQMVPCEAwBgYAINgVgBDM/T9Mvv0/UMz9P5S+/T8AAAAAAQAAANTP/D+QUAiA
8Mv9P9wA8D8BAAAAgCn7PzBn/T8DAAAAIw8GAAAAAAAQzP0/OBb7P+DCAED2wgBA
/////7UWCEAwZ/0/gGgIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUMz9P9Ro+z8xaPs/
AAAAAEwDAAADAAAAIw8GAP////9QzP0/1Gj7PzFo+z8kcPQ//////wQ0+z/Uz/w/
AAAAAIDM/T8AAAAAAAAAAGxo+z8AAAAAAAAAAAAAAAA4Fvs/AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjMz9PwAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
dGj9P8Bm/T9oaP0/
wGb9PwBo/T8W5bibJCf7PwDN/T90aP0/HCf7PwIAAAAEUv0/BFL9P3Ro/T/8Uf0/
FwAAAGxY/T93aWZpAMMds98RFkS0n2kAAAAAAGho/T8AAAAAIQAGABcAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFjj+j/A4/o/KOT6PwAAAAAAAAAA
AQAAAAAAAAB4KUA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACWhY
uBQIQMVPCEAwCAYAkOMTgIBn/T/YUf0/0Gf9PyBS/T8AAAAAAQAAAAQT+z+QUAiA
YGf9P9wA8D8BAAAAgCn7P5QCAAABAAAAhDADYBwAAADSnhOAYGf9P+DCAED2wgBA
/////7UWCECUAgAAgGgIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAKUAAAAAAAAAAAAAAJQCAAAAAAAAwGf9P6jE/D9gSPs/
AAAAAE4DAACoxPw/YEj7P//////AZ/0/qMT8P2BI+z+sxPw//////wEAAAAEE/s/
AAAAAABo/T8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAA
GgAAAFDkE0BQkEE/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAxo/T8AAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==
GOr6P4Do+j8M6vo/
gOj6P6Dp+j9FKTpXWLz9PyQn+z8Y6vo/HCf7PwEAAADo5fo/6OX6Pxjq+j/g5fo/
GAAAABDm+j9pcGMwAL4BrFyEbfYoYwAAAAAAAAzq+j8AAAAAIQAGABgAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFjj+j/A4/o/KOT6PwAAAAAAAAAA
AQAAAAAAAAB4KUA/AAAAAEgdAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAu01
uBQIQMVPCEAwAAYAzxEIgEDp+j+85fo/AAAAAATm+j8AAAAAAQAAAAAAAACQUAiA
IOn6P9wA8D8BAAAAgCn7P2A7/j8MC/s/AgAAAAAAAAClpaWlpaWlpQAAAAAAAAAA
AAAAALUWCEBgO/4/gGgIQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgOn6PwAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAKDp+j8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABaDgiAEDz+Pwwn+z+c+/o/
AAAAAAAAAACs6fo/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
================= CORE DUMP END =================
E (18359) esp_core_dump: Skipped 1 tasks with bad TCB!
E (18404) esp_core_dump: Crashed task has been skipped!
Rebooting...
```

**Comment by jumjum123** [comment]
Hmm, checked and it crashes. Will try to find the reason.

2017-08-25 11:25 GMT+02:00 Chevdor <notifications@github.com>:

**Comment by wilberforce** [comment]
@jumjum123 
Im wondering if this due to interrupts calling a function that needs a prefix to keep it in memory?

**Comment by jumjum123** [comment]
hmm, good point. I will check.
But this will take some time, just working on something else.

2017-08-28 11:39 GMT+02:00 wilberforce <notifications@github.com>:

**Comment by wilberforce** [comment]
Here is the core decoded:

```
 source scripts/provision.sh ESP32
export IDF_PATH=$ESP_IDF_PATH
ls../esp-idf/components/espcoredump/espcoredump.py  info_corefile -t b64 -c coredump.dat  espruino_1v93.227_esp32.elf
```

```
==================== ESP32 CORE DUMP START ====================

================== CURRENT THREAD REGISTERS ===================
pc             0x40127ea4       0x40127ea4 <esp_vApplicationIdleHook+40>
lbeg           0x0      0
lend           0x0      0
lcount         0x0      0
sar            0x0      0
ps             0x60820  395296
threadptr      <unavailable>
br             <unavailable>
scompare1      <unavailable>
acclo          <unavailable>
acchi          <unavailable>
m0             <unavailable>
m1             <unavailable>
m2             <unavailable>
m3             <unavailable>
expstate       <unavailable>
f64r_lo        <unavailable>
f64r_hi        <unavailable>
f64s           <unavailable>
fcr            <unavailable>
fsr            <unavailable>
a0             0x40085c38       1074289720
a1             0x3ffcd340       1073533760
a2             0x8      8
a3             0x1      1
a4             0x60023  393251
a5             0x3ffafd18       1073413400
a6             0x1      1
a7             0x0      0
a8             0x3ffb33d8       1073427416
a9             0x3ffcd320       1073533728
a10            0x0      0
a11            0x60820  395296
a12            0x60021  393249
a13            0x3ffafab0       1073412784
a14            0x3ffb0824       1073416228
a15            0x60720  395040

==================== CURRENT THREAD STACK =====================
#0  0x40127ea4 in esp_vApplicationIdleHook () at /mnt/c/Users/rhys/esp32/edge/EspruinoBuildTools/esp32/build/esp-idf/components/esp32/./freertos_hooks.c:52
#1  0x40085c38 in prvIdleTask (pvParameters=0x0) at /mnt/c/Users/rhys/esp32/edge/EspruinoBuildTools/esp32/build/esp-idf/components/freertos/./tasks.c:3322

======================== THREADS INFO =========================
  Id   Target Id         Frame
  9    process 8         xQueueGenericReceive (xQueue=0x3ffae5bc, pvBuffer=0x0, xTicksToWait=4294967295, xJustPeeking=0) at /mnt/c/Users/rhys/esp32/edge/EspruinoBuildTools/esp32/build/esp-idf/components/freertos/./queue.c:1452
  8    process 7         xQueueGenericReceive (xQueue=0x3ffd5150, pvBuffer=0x3ffd6750, xTicksToWait=4294967295, xJustPeeking=0) at /mnt/c/Users/rhys/esp32/edge/EspruinoBuildTools/esp32/build/esp-idf/components/freertos/./queue.c:1452
  7    process 6         xQueueGenericReceive (xQueue=0x3ffdbdc4, pvBuffer=0x3ffdcbd0, xTicksToWait=4294967295, xJustPeeking=0) at /mnt/c/Users/rhys/esp32/edge/EspruinoBuildTools/esp32/build/esp-idf/components/freertos/./queue.c:1452
  6    process 5         xQueueGenericReceive (xQueue=0x3ffd40a0, pvBuffer=0x3ffd4e40, xTicksToWait=4294967295, xJustPeeking=0) at /mnt/c/Users/rhys/esp32/edge/EspruinoBuildTools/esp32/build/esp-idf/components/freertos/./queue.c:1452
  5    process 4         xQueueGenericReceive (xQueue=0x3ffdb0b8, pvBuffer=0x3ffdbb20, xTicksToWait=4294967295, xJustPeeking=0) at /mnt/c/Users/rhys/esp32/edge/EspruinoBuildTools/esp32/build/esp-idf/components/freertos/./queue.c:1452
  4    process 3         prvTimerTask (pvParameters=0x0) at /mnt/c/Users/rhys/esp32/edge/EspruinoBuildTools/esp32/build/esp-idf/components/freertos/./timers.c:445
  3    process 2         xQueueGenericReceive (xQueue=0x3ffce3b0, pvBuffer=0x3ffcee40, xTicksToWait=85, xJustPeeking=0) at /mnt/c/Users/rhys/esp32/edge/EspruinoBuildTools/esp32/build/esp-idf/components/freertos/./queue.c:1452
  2    process 1         xQueueGenericReceive (xQueue=0x3ffdef74, pvBuffer=0x0, xTicksToWait=100, xJustPeeking=0) at /mnt/c/Users/rhys/esp32/edge/EspruinoBuildTools/esp32/build/esp-idf/components/freertos/./queue.c:1452
* 1    <main task>       0x40127ea4 in esp_vApplicationIdleHook () at /mnt/c/Users/rhys/esp32/edge/EspruinoBuildTools/esp32/build/esp-idf/components/esp32/./freertos_hooks.c:52

======================= ALL MEMORY REGIONS ========================
Name   Address   Size   Attrs
.rtc.text 0x400c0000 0x0 RW
.iram0.vectors 0x40080000 0x400 R XA
.iram0.text 0x40080400 0x14014 R XA
.dram0.data 0x3ffb0000 0x2614 RW A
.flash.rodata 0x3f400010 0x1e7e8 RW A
.flash.text 0x400d0018 0x95494 R XA
.coredump.tasks 0x3ffafd18 0x174 RW
.coredump.tasks 0x3ffcd280 0x164 RW
.coredump.tasks 0x3ffde724 0x174 RW
.coredump.tasks 0x3ffde4d0 0x248 RW
.coredump.tasks 0x3ffceee0 0x174 RW
.coredump.tasks 0x3ffcecf0 0x1e4 RW
.coredump.tasks 0x3ffcdbf8 0x174 RW
.coredump.tasks 0x3ffcda90 0x15c RW
.coredump.tasks 0x3ffdbbc8 0x174 RW
.coredump.tasks 0x3ffdba20 0x19c RW
.coredump.tasks 0x3ffd4efc 0x174 RW
.coredump.tasks 0x3ffd4d40 0x1b0 RW
.coredump.tasks 0x3ffdcc70 0x174 RW
.coredump.tasks 0x3ffdcad0 0x194 RW
.coredump.tasks 0x3ffd67ec 0x174 RW
.coredump.tasks 0x3ffd6640 0x1a0 RW
.coredump.tasks 0x3ffaea18 0x174 RW
.coredump.tasks 0x3ffae880 0x18c RW

===================== ESP32 CORE DUMP END =====================
```

**Comment by wilberforce** [comment]
possibly related?

https://www.bountysource.com/issues/40870147-tw-12230-gettimeofday-not-reentrant-when-used-with-rtc-registers-only-waiti-called-and-triggers-watchdog

**Comment by wilberforce** [comment]
Same abort() code dump as https://github.com/espruino/Espruino/issues/1176

Possibily related to the stack check watchdog code?

**Comment by wilberforce** [comment]
@jumjum123 

Searching for 

esp_vApplicationIdleHook
In the esp32 forum
https://www.esp32.com/viewtopic.php?f=13&t=1566&p=7318&hilit=esp_vApplicationIdleHook#p7318

Last comment is:

==============
problem solved!
increased task stack size in xTaskCreate

thanks!!!

Danny
===========

So in this pull request when the timer was moved we need to increase the stack size from 20000 to st least 22000

https://github.com/espruino/Espruino/commit/1b3f15a1951f5bc3fcb59cfa768abdb8840abb36#diff-da4c9462e3dc0765f7a8d798ee5a44c8R83

**Comment by wilberforce** [comment]
```
var count=0;

function blip() {
  digitalPulse(D21, 1, 15);
  console.log(count++);
}

function start() {
  setInterval(blip, 30);
}

start();
```

Fixed with https://github.com/espruino/Espruino/pull/1285
