### ISSUE TITLE
trying to build on Mac OSX

### ISSUE THREAD

**Issue by jcw** [espruino/Espruino#577]
Hello - I tried building Espruino on Mac OSX 10.10.5 w/ Xcode 7.0, and get this error:

```
Espruino$ STM32F4DISCOVERY=1 RELEASE=1 make
Generating platform configs
Generating pin info
Generating JS wrappers
WRAPPERSOURCES = src/jswrap_array.c src/jswrap_arraybuffer.c src/jswrap_date.c src/jswrap_error.c src/jswrap_espruino.c src/jswrap_flash.c src/jswrap_functions.c src/jswrap_interactive.c src/jswrap_io.c src/jswrap_json.c src/jswrap_modules.c src/jswrap_number.c src/jswrap_object.c src/jswrap_onewire.c src/jswrap_pin.c src/jswrap_pipe.c src/jswrap_process.c src/jswrap_serial.c src/jswrap_spi_i2c.c src/jswrap_stream.c src/jswrap_string.c src/jswrap_waveform.c libs/math/jswrap_math.c libs/graphics/jswrap_graphics.c libs/network/jswrap_net.c libs/network/http/jswrap_http.c libs/network/js/jswrap_jsnetwork.c libs/network/cc3000/jswrap_cc3000.c
DEFINES = -DGIT_COMMIT=32a66b2a1cc9b2c7043092aa788448dd252ea062 -DNO_ASSERT -DRELEASE -DBUILDNUMBER=" 394" -DUSE_USB_OTG_FS=1 -DUSE_DEBUGGER -DUSE_MATH -DUSE_GRAPHICS -DUSE_NET -DUSE_CC3000 -DSEND_NON_BLOCKING -DUSB -DSTM32F4 -DARM -DLINK_TIME_OPTIMISATION -DFAKE_STDLIB -DSTM32 -DUSE_STDPERIPH_DRIVER=1 -DSTM32F407VGT6 -DSTM32F4DISCOVERY -DSTM32F407xx -DEMBEDDED
CC libs/math/acosh.o
CC libs/math/asin.o
arm-none-eabi-gcc: error: 394": No such file or directory
arm-none-eabi-gcc: error: 394": No such file or directory
arm-none-eabi-gcc: error: 394": No such file or directory
arm-none-eabi-gcc: error: 394": No such file or directory
Traceback (most recent call last):
  File "scripts/build_jswrapper.py", line 163, in <module>
    jsondatas = common.get_jsondata(False)
  File "/Users/jcw/Documents/Playground/Espruino/scripts/common.py", line 128, in get_jsondata
    code = open(jswrap, "r").read()
IOError: [Errno 2] No such file or directory: '394"'
make: *** [libs/math/asin.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [gen/jswrapper.c] Error 1
make: *** [libs/math/acosh.o] Error 1
```

The ARM toochain is 4.9.3 20150529 (release) \[ARM/embedded-4_9-branch revision 224288].

All I can tell, is that the build number somehow gets into the file open error. Editing the Makefile and adding "COMMITS_SINCE_RELEASE=394" after line 95 to get rid of the extra space gets past this error.

The next error I get appears to indicate I need to install some more headers:

> (please ignore, it was a silly mistake...)

-jcw

**Comment by jcw** [comment]
Ooh, never mind on that second error: I forgot to set the STM32F4DISCOVERY env var again.

**Comment by gfwilliams** [comment]
Thanks - that's an interesting one. I wonder if it's actually a difference in `git` then, or I guess it could be `wc`'s behaviour.

Please can you try:

```
COMMITS_SINCE_RELEASE=$(shell git log --oneline $(LATEST_RELEASE)..HEAD | wc -l)
COMMITS_SINCE_RELEASE=`echo $COMMITS_SINCE_RELEASE` # Trim spaces
ifneq ($(COMMITS_SINCE_RELEASE),0)
DEFINES += -DBUILDNUMBER=\"$(COMMITS_SINCE_RELEASE)\"
endif
```

**Comment by jcw** [comment]
Thx - I added that space-triming trick, but (to my surprise) the bug seems to just move around:

```
Generating pin info
DEFINES = -DGIT_COMMIT=c3219b20bc933c1e518a762daf633363cfcb7065 -DBUILDNUMBER="OMMITS_SINCE_RELEASE " -DUSE_DEBUGGER -DUSE_FILESYSTEM -DUSE_MATH -DUSE_GRAPHICS -DUSE_NET -DUSB -DLINUX
CC src/jslex.o
```

Here's what I see:

```
Espruino$ git tag | grep RELEASE_ | sort | tail -1
RELEASE_1v72
Espruino$ git log --oneline RELEASE_1v72..HEAD | wc -l
     403
Espruino$ echo `git log --oneline RELEASE_1v72..HEAD | wc -l`
403
Espruino$ 
```

Probably some make expansion weirdness. All-in-one seems to fix it, though:

```
COMMITS_SINCE_RELEASE=$(shell echo `git log --oneline $(LATEST_RELEASE)..HEAD | wc -l`)
```

**Comment by gfwilliams** [comment]
Thanks for checking! I just committed the fix.

**Comment by jcw** [comment]
Confirmed. Many thanks.
